version: "3.9"
services:
  web:
  build:
    context: ./web
    image: image-web:latest
    container_name: teste_web
    ports:
      - 8000:8080
    volumes:
      - ./web:.
    networks:
      - web
    depends_on:
      - api
  api:
    context: ./api
    image: image-api:latest
    container_name: teste_api
    ports:
      - 3000:3080
    volumes:
      - ./api:.
    networks:
      - api
    depends_on:
      - database
  database:
    image: postgres:13.14-alpine3.19
    container_name: teste_db
    ports:
      - 5432:5439
    restart: always
    shm_size: 128mb
    networks:
      - database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
networks:
  web:
  api:
  database:
